name: Maven Action Workflow DBL
on:
  workflow_call:
    inputs:
      callerRepo:
        description: "callerRepo"
        required: true
        type: string
      buildCmd:
        description: "buildCmd"
        required: true
        type: string
      branchName:
        description: "branchName"
        required: true
        type: string
env:
  MY_CONTEXT: "Local variable: File scope to all jobs within the yml file"
  CALLER_REPO: ${{ inputs.callerRepo }}
  BUILD_CMD: ${{ inputs.buildCmd }}
  BRANCH_NAME: ${{ inputs.branchName }}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        id: initId
        run: |
          echo "Initialization and Configuration:"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  codeql:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: CODEQL Running
        id: codeqlId
        run: |
          echo "CODEQL Code Scan Running: Open 'Push on main' job output"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  build:
    needs: codeql
    strategy:
      matrix:
        version: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: buildId1
        uses: actions/checkout@v4
        with:
          repository: dblucas-ops/${{ env.CALLER_REPO }}
      - name: cache Dependancies
        continue-on-error: true
        id: cache
        uses: actions/cache@v3
        with:
          path: src
          key: dave-key-define-this
      - name: Build with Maven
        id: buildId2
        run: |
          echo "Build with Maven: ${{ matrix.version }}"
          mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
      - name: Interrogate Build Result1
        if: success()
        run: |
          echo "success"
          echo "success()"
          echo "Interrogate Build Result1..."
      - name: Interrogate Build Result2
        if: ${{steps.buildId2.outcome == 'success'}}
        run: |
          echo "steps.buildId2.outcome"
          echo "${{steps.buildId2.outcome}}"
          echo "Interrogate Build Result2..."
  post_action:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Post Action Running
        run: |
          echo "Post Action..."
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
